name: 🐛 Bug Report
description: Signaler un bug ou un dysfonctionnement
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug. Votre rapport nous aide à améliorer SalamBot.
        
        **Avant de continuer, vérifiez que :**
        - [ ] Vous avez cherché dans les issues existantes
        - [ ] Vous utilisez la dernière version
        - [ ] Le problème est reproductible

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement le problème rencontré
      placeholder: Décrivez le bug de manière claire et concise...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire ce bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: Décrivez ce qui devrait se passer...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
      placeholder: Décrivez ce qui se passe actuellement...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [ex: Windows 11, macOS 13, Ubuntu 22.04]
        - Navigateur: [ex: Chrome 118, Firefox 119]
        - Version Node.js: [ex: 18.17.0]
        - Version du projet: [ex: v1.2.3]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs et messages d'erreur
      description: Copiez-collez les logs ou messages d'erreur pertinents
      placeholder: Collez ici les logs, stack traces, ou messages d'erreur...
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran
      placeholder: Glissez-déposez vos images ici...

  - type: textarea
    id: additional
    attributes:
      label: Contexte additionnel
      description: Toute autre information utile
      placeholder: Ajoutez toute information supplémentaire qui pourrait aider...